### ISSUE TITLE
drat repository not building new versions?

### ISSUE THREAD

**Issue by lmullen** [ropensci/drat#17]
USAboundariesData is at version 0.3.1 on the master branch and has been for a week or two. https://github.com/ropensci/USAboundariesData

Running `install.packages("USAboundariesData", repos = c("http://packages.ropensci.org"))` installs version 0.3.0. 

I looked through the Circle CI logs but couldn't find any obvious errors. Is the drat repository building new versions of packages?

**Comment by cboettig** [comment]
Thanks for the heads up.  Looks like https://github.com/ropensci/drat/tree/gh-pages/src/contrib was last updated 28 days ago -- so the circle builds have not been pushing back up to github since we switched to circle 2.0 API (looks like we still didn't delete `circle.yml` either.  Weird.

The circle-ci config has a deploy block:

https://github.com/ropensci/drat/blob/1346304428c723b72c0f3c8c92e9b39fafb2ff99/.circleci/config.yml#L11-L17

but the logs give no sign of this being executed, so I must have something wrong in that config.  Will need to consult the Circle-CI 2.0 docs...

**Comment by cboettig** [comment]
@lmullen  fixed I think, try now?

**Comment by lmullen** [comment]
:+1: Works for me now. Thanks. This fix will let me push an update for USAboundaries to CRAN.
