### ISSUE TITLE
Unable to install 'genderdata' from this website

### ISSUE THREAD

**Issue by jhmaindonald** [ropensci/drat#6]
The attempt to install the 'genderdata' package from this website failed,
following the message I received when I tried to use the function gender_df()
in the 'gender' package:

```
> ...
The genderdata package needs to be installed.
Install the genderdata package? 

1: Yes
2: No

Selection: 1
Installing the genderdata package.
Installing package into ‘/Users/johnm1/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Error in value[[3L]](cond) : Failed to install the genderdata package.
 Please try installing the package for yourself 
 using the following command: 
 install.packages("genderdata", repo = "http://packages.ropensci.org")
> install.packages("genderdata", repo = "http://packages.ropensci.org")
Installing package into ‘/Users/johnm1/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Error in install.packages : Line starting '<html> ...' is malformed!
```

However the following was successful

```
devtools::install_github("lmullen/gender-data-pkg")
```

I now get the message that the package needs to be updated:

```
> z <- gender_df(hurricNamed, name_col="Name", year_col=c("Year"))
The genderdata package needs to be updated.
Install the genderdata package? 

1: Yes
2: No

Selection: 1
Installing the genderdata package.
Installing package into ‘/Users/johnm1/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Error in value[[3L]](cond) : Failed to install the genderdata package.
 Please try installing the package for yourself 
 using the following command: 
 install.packages("genderdata", repo = "http://packages.ropensci.org")
```

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_NZ.UTF-8/en_NZ.UTF-8/en_NZ.UTF-8/C/en_NZ.UTF-8/en_NZ.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gender_0.5.0    DAAG_1.22       lattice_0.20-33 knitr_1.10.5   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0         xml2_0.1.1          magrittr_1.5        splines_3.2.2      
 [5] devtools_1.8.0      MASS_7.3-43         R6_2.1.0            stringr_1.0.0      
 [9] httr_1.0.0          dplyr_0.4.2         tools_3.2.2         parallel_3.2.2     
[13] grid_3.2.2          nlme_3.1-121        genderdata_0.1      gamlss.data_4.3-0  
[17] latticeExtra_0.6-26 DBI_0.3.1           git2r_0.10.1        rversions_1.0.2    
[21] htmltools_0.2.6     survival_2.38-3     yaml_2.1.13         lazyeval_0.1.10    
[25] digest_0.6.8        assertthat_0.1      RColorBrewer_1.1-2  gamlss_4.3-5       
[29] curl_0.9.1          gamlss.dist_4.3-5   memoise_0.2.1       rmarkdown_0.7      
[33] stringi_0.5-5      
```

**Comment by cboettig** [comment]
Thanks for the bug report.  I can't replicate this, but perhaps the last drat update fixed it.  Can you try again and let us know if it persists?  @sckott @lmullen can you replicate the error here?

**Comment by lmullen** [comment]
@cboettig @sckott I am not able to reproduce this error. 

@jhmaindonald Thanks for the bug report. My guess is that the download of the package got hung since it is fairly large for an R package  (15.6 MB). Installing the package from GitHub was a good idea, but you got the old repository not the new one. Please try the following.

First, please try installing the package from gender:

```
library(gender)
install_genderdata_package()
```

If that doesn't work then you can try manually installing from GitHub:

```
devtools::install_github("ropensci/genderdata")
```

You need version `0.5.0` of both gender and genderdata.

If you have a bug with gender, feel free to [open an issue at that repository](https://github.com/ropensci/gender/issues).

**Comment by TSFdw** [comment]
I'm having a similar problem. I get 403 errors: 
install.packages("genderdata", repo = "http://packages.ropensci.org")
Installing package into ‘C:/Users/username/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘genderdata’ is not available (for R version 3.2.2)
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  cannot open: HTTP status was '403 Forbidden'
Warning in install.packages :
  unable to access index for repository http://packages.ropensci.org/bin/windows/contrib/3.2

And using dev tools hangs. 15 MB should take me a couple seconds here, but it's been going for about 10 minutes so far.

> devtools::install_github("ropensci/genderdata")
> Downloading github repo ropensci/genderdata@master

**Comment by lmullen** [comment]
@TSFdw Thanks for the bug report. Could you please try the following? I assume that you are on Windows with R 3.2.2.

```
install.packages("genderdata", repo = "http://packages.ropensci.org", type = "source")
```

If that doesn't work, I think that re-running `devtools::install_github("ropensci/genderdata")` will work.  Sometimes GitHub hangs on large files for me.

**Comment by lmullen** [comment]
@cboettig I've been testing installing source/binary packages with versions of R compiled with different options. I.e., the Mac package installer for R 3.2.2 sets `getOptions("pktType")` to `"both"`. But it appears that genderdata is now missing from the rOpenSci package repository; I can't find it with `install.packages()` or `available.packages()`. Is there a problem with the build or the repository index?

**Comment by cboettig** [comment]
@lmullen Looks like an incomplete PACKAGES list was uploaded.  Looking into if that was a one-time transfer error or a persistent issue...

**Comment by lmullen** [comment]
@cboettig I noticed in the logs earlier that more packages are being built than are being added to the drat repository. E.g., there is a line

```
*** [build] ropensci/gender/
*** [build] ropensci/genderdata/
```

and a line

```
*** [drat] ropensci/gender/
```

But there is no `[drat]` line for genderdata or many of the other packages. Don't know if that is helpful or not.

**Comment by jhmaindonald** [comment]
The Aug 25 message seems only today to have appeared in my mailer.

install_genderdata_package() gives me the same error as before, and the suggestion
that I try install.packages("genderdata", repo = "http://packages.ropensci.org”) gives me
(I tried this under Windows, as I did not5 want to mess up the already successful 
installation from github.)

> install.packages("genderdata", repo = "http://packages.ropensci.org")
> Installing package into ‘C:/Users/johnm1/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘genderdata’ is not available (for R version 3.2.2)
> Warning in install.packages :
>   cannot open: HTTP status was '403 Forbidden'
> Warning in install.packages :
>   cannot open: HTTP status was '403 Forbidden'
> Warning in install.packages :
>   unable to access index for repository http://packages.ropensci.org/bin/windows/contrib/3.2 http://packages.ropensci.org/bin/windows/contrib/3.2

The installation using devtools::install_github("ropensci/genderdata”)
has worked fine (this under MacOS), now giving me version 0.5.0

**Comment by lmullen** [comment]
@jhmaindonald For now `devtools::install_github("ropensci/genderdata”)` is your best option, and works just as well as the `install.packages()` route.

**Comment by cboettig** [comment]
@lmullen Good catch -- I think I see what's going on.  We are only writing the PACKAGES file for the packages that changed, because I wasn't pulling the previous PACKAGES list down and we added a step to stop pushing up packages that had not changed.  (Another gotcha of pushing to S3 instead of GitHub, as in the original drat model).  Fixing this now and seeing if that solves the issue.

**Comment by lmullen** [comment]
@cboettig After your fixes the `/src/contrib/PACKAGES` file now has genderdata and all the other packages which have not changed. However, `available.packages()` (which is called by `install.packages()`) doesn't download `/src/contrib/PACKAGES` directly; it downloads `/src/contrib/PACKAGES.gz`. That file seems to be only the packages that have been changed; i.e., the same file as last night before your fixes.

**Comment by lmullen** [comment]
@cboettig The changes you've recently made seem to have worked. I can successfully install the package again.

To recap, here is what I learned. Windows versions of R and Mac pre-compiled versions of R (thus, most R users) return `"both"` for `getOption("pkgType")`. So when those users use `available.packages()` they go looking for binary packages first and get an HTML error, probably a 404 error, instead of the DCF file that is expected. I think that the way to fix this is to have an empty `PACKAGES` and `PACKAGES.gz` in all the myriad places that it might go in a CRAN-style repository, e.g. `/bin/macosx/contrib/r-release/PACKAGES`. Thus no available binary packages will be reported instead of there being an error message, and `available.packages()` will go on to use the source packages. This will not be a problem for packages which do not require compilation. I expect that packages that do require compilation will fail on installations that don't have the necessary tools.

Or, the simplest thing to do is to recommend that people always install with `type = "source"`. Perhaps that should be added to the repository documentation?

I've got a patch to the gender package which does that, which I'll push to CRAN. I think that resolves the issue specifically with gender.

**Comment by cboettig** [comment]
@lmullen thanks for all the help in trouble-shooting.  I _think_ that if I just add the right but empty binary structure then we should be able to continue to dispense with `type="source"` for all platforms.  I've just pushed that to circle now, should build in a bit.  Would be great if you could check if mac could then install without `type="source"`, since I don't have a mac handy.

**Comment by cboettig** [comment]
@lmullen Okay, lemme know when you have a chance to give it a test on a Mac without `type="source"` and see if we still get the same error.

**Comment by lmullen** [comment]
Here is what I get in the CRAN pre-compiled Mac version of R 3.2.2:

```
> getOption("pkgType")
[1] "both"
> install.packages("genderdata", repos = "http://packages.ropensci.org")
Installing package into '/Users/lmullen/Library/R/3.2/library'
(as 'lib' is unspecified)
Error: Line starting '<html> ...' is malformed!
```

I assume that this commit (0962012febb) is the one with the relevant changes. But I can't find empty `PACKAGES` or `PACKAGES.gz` files at the places I would expect them:

http://packages.ropensci.org/bin/macosx/contrib/3.2/PACKAGES
http://packages.ropensci.org/bin/macosx/contrib/3.2/PACKAGES.gz
http://packages.ropensci.org/bin/macosx/contrib/r-release/PACKAGES
http://packages.ropensci.org/bin/macosx/contrib/r-release/PACKAGES.gz

Browsing CRAN https://cran.rstudio.com/bin/macosx/contrib/, will it be necessary to have the PACKAGEs files in directories with all the R version numbers?

**Comment by cboettig** [comment]
Maybe I just need an empty packages.gz file?  Can you tell what file R
thinks it is trying to open when it complains about malformed html?

On Thu, Sep 3, 2015, 12:15 PM Lincoln Mullen notifications@github.com
wrote:

> Here is what I get in the CRAN pre-compiled Mac version of R 3.2.2:
> 
> > getOption("pkgType")
> > [1] "both"
> > install.packages("genderdata", repos = "http://packages.ropensci.org")
> > Installing package into '/Users/lmullen/Library/R/3.2/library'
> > (as 'lib' is unspecified)
> > Error: Line starting '<html> ...' is malformed!
> 
> I assume that this commit (0962012
> https://github.com/ropensci/drat/commit/0962012febb482503397e80599637264682b7071)
> is the one with the relevant changes. But I can't find empty PACKAGES or
> PACKAGES.gz files at the places I would expect them:
> 
> http://packages.ropensci.org/bin/macosx/contrib/3.2/PACKAGES
> http://packages.ropensci.org/bin/macosx/contrib/3.2/PACKAGES.gz
> http://packages.ropensci.org/bin/macosx/contrib/r-release/PACKAGES
> http://packages.ropensci.org/bin/macosx/contrib/r-release/PACKAGES.gz
> 
> Browsing CRAN https://cran.rstudio.com/bin/macosx/contrib/, will it be
> necessary to have the PACKAGEs files in directories with all the R version
> numbers?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/drat/issues/6#issuecomment-137545874.
> 
> ## 

http://carlboettiger.info

**Comment by lmullen** [comment]
I stepped through `install.packages` and I'm pretty sure it is looking for

```
http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2/PACKAGES.gz
```

**Comment by lmullen** [comment]
It looks like `available.packages` checks for `PACKAGES.gz` first and if it gets an error it checks for `PACKAGES`.

**Comment by cboettig** [comment]
Ah, okay, as usual I'm an idiot and I think this is mostly another S3 issue -- I had added the empty PACKAGES in the `bin` file now but I hadn't granted public visible permissions to it in S3, so R was getting an access error XML file that it didn't like.  I just toggled the permissions -- can you try now?

(I still haven't added an empty `PACKAGES.gz`, but if you're right about the fallback then maybe shouldn't cause a problem... maybe...)

**Comment by lmullen** [comment]
I'm getting a 404 error not the 403 error, which reflects your change. You've got the file at

http://packages.ropensci.org/bin/macosx/contrib/3.2/PACKAGES

but there also has to be one at 

http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2/PACKAGES

since there are `mac.binary` and `mac.binary.mavericks` options.

**Comment by cboettig** [comment]
cool, I think we're getting closer.  try now?

**Comment by lmullen** [comment]
Works!  This works just fine.

```
> getOption("pkgType")
[1] "both"
> install.packages("genderdata", repos = "http://packages.ropensci.org")
```

I guess we no longer have to say "drat." (I'm so sorry. I just couldn't resist.)

**Comment by cboettig** [comment]
Very nice, thanks for checking.  Looks like we can close but @jhmaindonald or anyone feel free to re-open if anything is still bumpy.

**Comment by lmullen** [comment]
@cboettig Looks like the `PACKAGES` file is only showing packages that changed again. As of now, it only lists two packages:

http://packages.ropensci.org/src/contrib/PACKAGES
