### ISSUE TITLE
Problem with ropensci drat url

### ISSUE THREAD

**Issue by sckott** [ropensci/drat#7]
@cboettig I keep getting 

`Error in install.packages : Line starting '<html> ...' is malformed!`

After any use of our drat repo, e.g, 

``` r
options(repos = c("http://packages.ropensci.org", "https://cran.rstudio.com/"))
install.packages("gender")
```

gives the above

**Comment by cboettig** [comment]
Hmm, thanks for confirming the issue in #6 .  Weird that @lmullen and I cannot replicate -- Lincoln, are you on a Mac platform?  

@sckott Can you try: 

``` r
install.packages("gender", type = "source")
```

I thought R >= 3.1.0 or so handled that automatically, but maybe I'm missing the part of the directory that lets Mac client figure out not to look for binaries.

If that doesn't work, any chance you can drop into `options(error=recover)` and let me know what R is trying to do when it hits the error?

**Comment by sckott** [comment]
oh weird, in R on the cli, it works with warning

``` r
<r> install.packages("genderdata")
Warning: unable to access index for repository http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2
installing the source package ‘genderdata’

trying URL 'http://packages.ropensci.org/src/contrib/genderdata_0.5.0.tar.gz'
Content type 'application/octet-stream' length 16313114 bytes (15.6 MB)
==================================================
downloaded 15.6 MB

 :) R version 3.2.2 (2015-08-14)* installing *source* package ‘genderdata’ ...
** R
** data

...
```

but not in RStudio - i'll see if there's some option I have in rstudio that could be causing this

**Comment by lmullen** [comment]
@cboettig I'm on a Mac, but I've also compiled R via homebrew rather than than using a compiled binary from R Project or homebrew. I think that means that my version of R does not try to install Mavericks binaries so that it always tries source packages.

**Comment by sckott** [comment]
somebody else is reporting this problem https://support.rstudio.com/hc/communities/public/questions/205370887-install-packages-problem

**Comment by lmullen** [comment]
FWIW, 

```
install.packages("gender", repos = c("http://packages.ropensci.org", "https://cran.rstudio.com/"))
```

works for me in rocker/r-base.

**Comment by sckott** [comment]
Tried with R 3.2.1, R 3.2.2, and R devel - In R on the cli, First two worked installing from our drat with `install.packages("gender")`, but devel didn't work. In Rstudio, none work. Seems like mostly an RStudio  problem. 

Interesting, @lmullen - i imagine most or our users will not be installing R from homebrew :(

**Comment by cboettig** [comment]
@sckott Nice work, sounds like it is due to Mac looking for binaries.  We should probably file a bug report for RStudio on this, but meanwhile I might be able to fix the error/warning by properly adding directories for Mac/Windows binaries to the drat repo, even if they are empty. 

@eddelbuettel, have you seen this error on drat repos before?    

@sckott can you get the error from RStudio if you install a package from @eddelbuettel's drat repo?

**Comment by sckott** [comment]
this may be related https://support.rstudio.com/hc/en-us/articles/206827897  - turning the setting off in RStudio makes it work, but with a bunch of warnings:

``` r
#> install.packages("gender")
#> Warning in install.packages :
#>   cannot open: HTTP status was '403 Forbidden'
#> Warning in install.packages :
#>   cannot open: HTTP status was '403 Forbidden'
#> Warning in install.packages :
#>   unable to access index for repository http://packages.ropensci.org/bin/macosx/mavericks/contrib/3.2
#> 
#>   There is a binary version available but the source version is later:
#>        binary     source needs_compilation
#> gender  0.4.3 0.5.0.9001             FALSE
#> 
#> installing the source package ‘gender’
#> 
#> trying URL 'http://packages.ropensci.org/src/contrib/gender_0.5.0.9001.tar.gz'
#> Content type 'application/octet-stream' length 77047 bytes (75 KB)
#> ==================================================
#> downloaded 75 KB
#> 
#>  :) R version 3.2.2 (2015-08-14)
#> * installing *source* package ‘gender’ ...
#> ** R
#> ** inst
#> ** preparing package for lazy loading
#> ** help
#> *** installing help indices
#> ** building package indices
#> ** installing vignettes
#> ** testing if installed package can be loaded
#> * DONE (gender)
```

**Comment by lmullen** [comment]
@sckott re: homebrew. Yes, definitely. I'm thinking about whether I should include `install.packages(type = "source")` to be safe when installing packages from inside a function in a package.

**Comment by lmullen** [comment]
This line in @sckott's output is interesting:

#>   There is a binary version available but the source version is later:
#>        binary     source needs_compilation
#> gender  0.4.3 0.5.0.9001             FALSE

Any idea why there would be an older binary version of gender? `0.5.0.9001` is current on the master branch.

**Comment by cboettig** [comment]
The older binary is probably the one on the CRAN RStudio mirror

On Mon, Aug 24, 2015, 5:29 PM Lincoln Mullen notifications@github.com
wrote:

> This line in @sckott https://github.com/sckott's output is interesting:
> 
> #> There is a binary version available but the source version is later:
> #> binary source needs_compilation
> #> gender 0.4.3 0.5.0.9001 FALSE
> 
> Any idea why there would be an older binary version of gender? 0.5.0.9001
> is current on the master branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/drat/issues/7#issuecomment-134423998.
> 
> ## 

http://carlboettiger.info

**Comment by eddelbuettel** [comment]
Sorry. Just out of a Docker meetup here in Chitown.  Have nothing special to add here -- I don't work with mac binaries for lack of ... even a single mac anywhere in my life.   The inital html error also happens with curl directs failing etc pp.   I'd try to trace down the actual URL that was tried but it looks like you all are on that trail already...

drat itself appears to be very happy using https in default mode at GH (which serves https just) using with R 3.2.2 which has it on by default, or using

``` .r
options(download.file.method="libcurl")
```

with older R.    But you guys do of course on being different by using neither the drat naming scheme nor the default hosting so you are really on own by your own choice :)  

Let me know if I can help otherwise.

**Comment by kevinushey** [comment]
AFAICS the issue here is that the RStudio CRAN mirror is serving a 404 page, and R is treating that as though it were the contents of a package. I'm not sure whether this is an issue in the CRAN server itself, or how R is configured (perhaps as @eddelbuettel said it's related to whether or not `libcurl` is being used when accessing a repository over `https`?)

**Comment by eddelbuettel** [comment]
There are related issues as some curl builds _do_ follow redirects and others _do not_ (as all of you may have seen Kurt falsely flagging URL reached by redirect when he runs `--as-cran`).  Super annoying.

Not sure what I could do here:  `drat` itself  is so simple, it just trusts `update.packages()` and friends.  So I'd call for a  `¯\_(ツ)_/¯` from me ...

**Comment by cboettig** [comment]
This should be fixed, now that we have the mac/windows `/bin` directory structure.

**Comment by eddelbuettel** [comment]
:+1:
